### ISSUE TITLE
02 assertion text is incorrect

### ISSUE THREAD

**Issue by jessejanderson** [seven1m/30-days-of-elixir#22]
Line 29-33:
```
test "assert_in_delta asserts that val1 and val2 differ by no more than delta." do
  assert_in_delta 1, # actual
                  5, # expected
                  6  # delta
end
```

The text should says "val1 and val2 differ by less than delta".

If you change `val2` to `7` you get this error (instead of passing as the text implies you would):
`Expected the difference between 1 and 7 (6) to be less than 6`

**Comment by seven1m** [comment]
PRs welcome :-)
