### ISSUE TITLE
broken link in second example

### ISSUE THREAD

**Issue by eddwardo** [seven1m/30-days-of-elixir#9]
http://elixir-lang.org/getting_started/ex_unit/1.html in 30-days-of-elixir 02-unit-testing.exs returns 404

**Comment by parroty** [comment]
I've replaced the links throwing 404 with related ones under http://elixir-lang.org (I couldn't find exact match for some of them, as document structure has changed).

**Comment by eddwardo** [comment]
+1

**Comment by seven1m** [comment]
Cool thanks!
